/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import deMessage from '../locales/de/messages.json';
import enMessage from '../locales/en/messages.json';
import frMessage from '../locales/fr/messages.json';
import itMessage from '../locales/it/messages.json';

export function getMessageFromLocale(locale: string) {
  switch (locale) {
    case 'de':
      return deMessage;
    case 'en':
      return enMessage;
    case 'fr':
      return frMessage;
    case 'it':
      return itMessage;
    default:
      throw new Error('Unsupported locale');
  }
}

export const defaultLocale = (() => {
  const locales = ['de', 'en', 'fr', 'it'];
  const firstLocale = locales[0];
  const defaultLocale = Intl.DateTimeFormat().resolvedOptions().locale.replace('-', '_');
  if (locales.includes(defaultLocale)) {
    return defaultLocale;
  }
  const defaultLocaleWithoutRegion = defaultLocale.split('_')[0];
  if (locales.includes(defaultLocaleWithoutRegion)) {
    return defaultLocaleWithoutRegion;
  }
  return firstLocale;
})();
