/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type deMessage from '../locales/de/messages.json';
import type enMessage from '../locales/en/messages.json';
import type frMessage from '../locales/fr/messages.json';
import type itMessage from '../locales/it/messages.json';

export type MessageKey = keyof typeof deMessage &
  keyof typeof enMessage &
  keyof typeof frMessage &
  keyof typeof itMessage;

export type DevLocale = 'de' | 'en' | 'fr' | 'it';
